### ISSUE TITLE
Add Django Content

### ISSUE THREAD

**Issue by michael-yin** [marcoroth/turbo_power#139]
@marcoroth 

I am a Django developer and maintainer of [django-turbo-helper](https://github.com/rails-inspire-django/django-turbo-helper), which is turbo helper for Django.

Inspired by "turbo_power-rails", I just added some custom actions to the project, so Django developer can also use `morph`, `turbo_frame_reload` and other actions in Django, with the same way "turbo_power-rails" does.

Here is the source code https://github.com/rails-inspire-django/django-turbo-helper/blob/main/src/turbo_helper/turbo_power.py if you are interested.

I want to add the link to the doc of this project, to tell people this project can also work in Django, and I am sure many Django developers will like it. 👍 

If you think this is good to go, please let me know and I will create PR in a bit.

Thanks for your great work on this project.

**Comment by marcoroth** [comment]
Hey @michael-yin, this is great!

Please feel free to add something to README to also mention the Django project. It would also be great to have something on https://hotwire.io about it down the road.
