### ISSUE TITLE
`redirect_to` Action: rename `action` attribute to `action_name`

### ISSUE THREAD

**Issue by marcoroth** [marcoroth/turbo_power#15]
The `redirect_to` action has an `action` attribute which is being passed to `Turbo.visit(..., { action })` to control the Turbo visit behaviour.

But the `action` attribute name is clashing with the `<turbo-stream>` element, since it's using the `action` attribute for determining the stream action to execute.

We should rename the attribute for the `redirect_to` action to either `action_name` or `turbo_action`.

**Comment by pySilver** [comment]
`turbo_action` sounds better IMO

**Comment by marcoroth** [comment]
Yeah, I would be fine with `turbo_action`. This makes it more explicit!
