### ISSUE TITLE
Use `set_storage_item`

### ISSUE THREAD

**Issue by seb-jean** [marcoroth/turbo_power#227]
How to use `set_storage_item` with a `<select>`. Should we create a Stimulus controller?
The goal: I would like to set a value for an item of the `localStorage` at the change event of the `<select>`.

**Comment by marcoroth** [comment]
Hey @seb-jean, I think you shouldn't be using Turbo Power for that. 

All the `set_storage_item` action does it calling `localStorage.setItem(key, value)` under the hood. This is something I personally would just wrap into a Stimulus Controller. 

Unless the use-case is that the `<select>` fires off a request and the value you want to set is dynamic and coming from the backend. For that case, you could either just `respond_to` the Turbo request from your controller action and call the `set_storage_item` Ruby helper on `turbo_stream`.

I hope this helps!

**Comment by marcoroth** [comment]
Going to close this for now, feel free to re-open if you need any more assistance, thank you!
